### ISSUE TITLE
done_p?

### ISSUE THREAD

**Issue by zhouzypaul** [camall3n/actgen#1]
https://github.com/camall3n/actgen/blob/04af9f46d576e68503b160d4d2e56183850853f0/actgen/train.py#L61

should this line be `done_p` instead? so that the while loop ends when it reaches max episode step.
@camall3n

**Comment by camall3n** [comment]
Great question. The difference between `done` and `done_p` is subtle. I actually thought I changed the name of `done_p` to `terminal`. But either way, `done` means the environment needs to be reset (for any reason), whereas `done_p` specifically means the episode ended with a terminal state before the timeout. When learning a Q function you want to avoid bootstrapping for terminal states but not timeouts.

**Comment by zhouzypaul** [comment]
what do you mean by `timeouts`? is it any time when `done` is True?

**Comment by camall3n** [comment]
The episode can end for two reasons: terminal states and timeouts. A terminal state can occur at any timestep; a timeout can only occur at the last timestep. If the agent is learning Q via bootstrapping, it needs to avoid bootstrapping after a terminal state, since there's no "next state" to bootstrap off of. However for a timeout, unless the agent knows the timestep (which it generally doesn't for cartpole) it should still bootstrap, since the next state is valid. Otherwise if the agent is balancing the pole successfully at the last timestep, it will erroneously think that balancing the pole leads to less return than it actually does.

**Comment by zhouzypaul** [comment]
ohhh got it. Thanks for the explanaiton!
